/*
 * Generated by asn1c-0.9.29 (http://lionet.info/asn1c)
 * From ASN.1 module "Ieee1609Dot3Wsa"
 * 	found in "../../asn/1609.3-2020/Ieee1609Dot3Wsa.asn"
 * 	`asn1c -fno-include-deps -fcompound-names-all -gen-OER -fincludes-quoted -pdu=auto`
 */

#ifndef	_Ieee1609Dot3Wsa_ExtendedChannelInfo_H_
#define	_Ieee1609Dot3Wsa_ExtendedChannelInfo_H_


#include "asn_application.h"

/* Including external dependencies */
#include "Ieee1609Dot3Wsa_MedType.h"
#include "ANY.h"
#include "asn_ioc.h"
#include "NULL.h"
#include "Ieee1609Dot3Wsa_ChannelInfo.h"
#include "Ieee1609Dot3Wee_LTEv2xChannelInfo.h"
#include "OPEN_TYPE.h"
#include "constr_CHOICE.h"
#include "constr_SEQUENCE.h"

#ifdef __cplusplus
extern "C" {
#endif

/* Dependencies */
typedef enum Ieee1609Dot3Wsa_ExtendedChannelInfo__value_PR {
	Ieee1609Dot3Wsa_ExtendedChannelInfo__value_PR_NOTHING,	/* No components present */
	Ieee1609Dot3Wsa_ExtendedChannelInfo__value_PR_NULL,
	Ieee1609Dot3Wsa_ExtendedChannelInfo__value_PR_NULL_1,
	Ieee1609Dot3Wsa_ExtendedChannelInfo__value_PR_Ieee1609Dot3Wsa_ChannelInfo,
	Ieee1609Dot3Wsa_ExtendedChannelInfo__value_PR_Ieee1609Dot3Wee_LTEv2xChannelInfo
} Ieee1609Dot3Wsa_ExtendedChannelInfo__value_PR;

/* Ieee1609Dot3Wsa_ExtendedChannelInfo */
typedef struct Ieee1609Dot3Wsa_ExtendedChannelInfo {
	Ieee1609Dot3Wsa_MedType_t	 medId;
	struct Ieee1609Dot3Wsa_ExtendedChannelInfo__value {
		Ieee1609Dot3Wsa_ExtendedChannelInfo__value_PR present;
		union Ieee1609Dot3Wsa_ExtendedChannelInfo__value_u {
			NULL_t	 NULL_;
			NULL_t	 NULL_1;
			Ieee1609Dot3Wsa_ChannelInfo_t	 Ieee1609Dot3Wsa_ChannelInfo;
			Ieee1609Dot3Wee_LTEv2xChannelInfo_t	 Ieee1609Dot3Wee_LTEv2xChannelInfo;
		} choice;
		
		/* Context for parsing across buffer boundaries */
		asn_struct_ctx_t _asn_ctx;
	} value;
	
	/* Context for parsing across buffer boundaries */
	asn_struct_ctx_t _asn_ctx;
} Ieee1609Dot3Wsa_ExtendedChannelInfo_t;

/* Implementation */
extern asn_TYPE_descriptor_t asn_DEF_Ieee1609Dot3Wsa_ExtendedChannelInfo;
extern asn_SEQUENCE_specifics_t asn_SPC_Ieee1609Dot3Wsa_ExtendedChannelInfo_specs_1;
extern asn_TYPE_member_t asn_MBR_Ieee1609Dot3Wsa_ExtendedChannelInfo_1[2];

#ifdef __cplusplus
}
#endif

#endif	/* _Ieee1609Dot3Wsa_ExtendedChannelInfo_H_ */
#include "asn_internal.h"
